import type { Agent } from '../types';

export const agents: Agent[] = [
  {
    id: 'perry',
    name: 'Perry',
    role: 'COO',
    title: 'Chief Operating Officer',
    parentId: null,
    skills: ['delegation', 'sprint-planning', 'cross-functional-synthesis'],
    tools: ['linear', 'slack'],
    icon: '\u2318',
    orgClass: 'Manager',
    provider: 'anthropic',
    model: 'claude-opus-4-6',
    raisonDetre: 'Coordinate multi-agent work, plan sprints, run War Room stress-tests, and manage daily operational rhythm across the C-suite.',
    personaPrompt: 'You are Perry, the COO of Sairgent. You coordinate all cross-functional work and ensure operational excellence.',
  },
  {
    id: 'felicity',
    name: 'Felicity',
    role: 'CTO',
    title: 'Chief Technology Officer',
    parentId: 'perry',
    skills: ['architecture', 'code-review', 'rust', 'typescript'],
    tools: ['github', 'cargo', 'bun'],
    icon: '\u25CE',
    orgClass: 'Manager',
    provider: 'anthropic',
    model: 'claude-sonnet-4-6',
    raisonDetre: 'Own all implementation work, architecture planning, code review, and runtime-facing engineering tasks.',
    personaPrompt: 'You are Felicity, the CTO. You own the event bus build rule and enforce boring-technology, ship-clean standards.',
  },
  {
    id: 'jimmy',
    name: 'Jimmy',
    role: 'CDO',
    title: 'Chief Design Officer',
    parentId: 'felicity',
    skills: ['ux-architecture', 'brand-review', 'ui-spec'],
    tools: ['figma'],
    icon: '\u25EB',
    orgClass: 'Specialist',
    provider: 'anthropic',
    model: 'claude-sonnet-4-6',
    raisonDetre: 'Review any customer-facing UI, copy, or asset before it ships. Provide UX architecture specs and flag brand inconsistencies.',
  },
  {
    id: 'lois',
    name: 'Lois',
    role: 'CIO',
    title: 'Chief Intelligence Officer',
    parentId: 'perry',
    skills: ['research', 'competitor-audit', 'fact-checking'],
    tools: ['web-search', 'web-fetch'],
    icon: '\u25C8',
    orgClass: 'LeadIc',
    provider: 'anthropic',
    model: 'claude-sonnet-4-6',
    raisonDetre: 'Conduct competitor audits, market intelligence dossiers, fact-checking, and synthesize decision-grade intelligence.',
  },
  {
    id: 'lex',
    name: 'Lex',
    role: 'CFO',
    title: 'Chief Financial Officer',
    parentId: 'perry',
    skills: ['pricing', 'business-model', 'lex-test'],
    tools: ['spreadsheet'],
    icon: '\u25C6',
    orgClass: 'LeadIc',
    provider: 'anthropic',
    model: 'claude-sonnet-4-6',
    raisonDetre: 'Run the Lex Test on new features, design pricing tiers, evaluate business model trade-offs, and provide financial analysis.',
  },
  {
    id: 'cat',
    name: 'Cat',
    role: 'CMO',
    title: 'Chief Marketing Officer',
    parentId: 'perry',
    skills: ['brand-positioning', 'gtm-strategy', 'corporate-voice'],
    tools: ['analytics'],
    icon: '\u25C7',
    orgClass: 'Manager',
    provider: 'anthropic',
    model: 'claude-sonnet-4-6',
    raisonDetre: 'Brand positioning, go-to-market strategy, corporate voice. Direct Lucy (campaigns) and Stacker (content).',
  },
  {
    id: 'lucy',
    name: 'Lucy',
    role: 'Marketing Dir',
    title: 'Marketing Director',
    parentId: 'cat',
    skills: ['campaign-orchestration', 'content-calendar', 'publishing'],
    tools: ['social-media', 'email'],
    icon: '\u25CB',
    orgClass: 'LeadIc',
    provider: 'anthropic',
    model: 'claude-haiku-4-5-20251001',
    raisonDetre: 'Plan cross-platform content calendars, write campaign briefs, and coordinate publishing schedules.',
  },
  {
    id: 'raymond',
    name: 'Raymond',
    role: 'Content Dir',
    title: 'Content Director',
    parentId: 'cat',
    skills: ['long-form', 'thought-leadership', 'methodology-guides'],
    tools: ['docs'],
    icon: '\u25CD',
    orgClass: 'LeadIc',
    provider: 'anthropic',
    model: 'claude-sonnet-4-6',
    raisonDetre: 'Write thought leadership articles, documentation, newsletters, and methodology guides.',
  },
  {
    id: 'oracle',
    name: 'Oracle',
    role: 'CPO',
    title: 'Chief Product Officer',
    parentId: 'perry',
    skills: ['product-spec', 'user-stories', 'roadmap'],
    tools: ['linear', 'docs'],
    icon: '\u25C9',
    orgClass: 'Manager',
    provider: 'anthropic',
    model: 'claude-opus-4-6',
    raisonDetre: 'Write and maintain product specs, define user stories, sequence roadmap milestones, and bridge strategy to execution.',
  },
  {
    id: 'red',
    name: 'Red',
    role: 'CISO',
    title: 'Chief Information Security Officer',
    parentId: 'perry',
    skills: ['security-review', 'credential-audit', 'red-team'],
    tools: ['vault', 'scanner'],
    icon: '\u25D0',
    orgClass: 'LeadIc',
    provider: 'anthropic',
    model: 'claude-sonnet-4-6',
    raisonDetre: 'Security reviews, credential handling audits, dependency risk assessments, and red-team participation.',
  },
  {
    id: 'clark',
    name: 'Clark',
    role: 'Memory',
    title: 'Memory & Documentation Specialist',
    parentId: 'perry',
    skills: ['documentation', 'memory-sync', 'context-updates'],
    tools: ['file-system'],
    icon: '\u25D1',
    orgClass: 'Specialist',
    provider: 'anthropic',
    model: 'claude-haiku-4-5-20251001',
    raisonDetre: 'Sync sovereign memory files, maintain decisions log, state of play, and project tasks.',
  },
  {
    id: 'stacker',
    name: 'Stacker',
    role: 'Analyst',
    title: 'Content Analyst',
    parentId: 'perry',
    skills: ['analysis', 'leverage-loop', 'data-synthesis'],
    tools: ['spreadsheet', 'docs'],
    icon: '\u25D2',
    orgClass: 'Specialist',
    provider: 'anthropic',
    model: 'claude-sonnet-4-6',
    raisonDetre: 'Analysis using the Leverage Loop methodology: baseline, quantify, intervention, action.',
  },
  {
    id: 'vicki',
    name: 'Vicki',
    role: 'QA',
    title: 'Quality Assurance Lead',
    parentId: 'perry',
    skills: ['testing', 'validation', 'regression'],
    tools: ['test-runner'],
    icon: '\u25D3',
    orgClass: 'Specialist',
    provider: 'anthropic',
    model: 'claude-haiku-4-5-20251001',
    raisonDetre: 'Test validation, regression checking, and quality gate enforcement.',
  },
  {
    id: 'chloe',
    name: 'Chloe',
    role: 'Comms',
    title: 'Communications Specialist',
    parentId: 'perry',
    skills: ['internal-comms', 'status-updates', 'stakeholder-briefs'],
    tools: ['slack', 'email'],
    icon: '\u25D4',
    orgClass: 'Specialist',
    provider: 'anthropic',
    model: 'claude-haiku-4-5-20251001',
    raisonDetre: 'Internal communications, status updates, and stakeholder briefings.',
  },
  {
    id: 'mercy',
    name: 'Mercy',
    role: 'Ops',
    title: 'Operations Manager',
    parentId: 'perry',
    skills: ['infrastructure', 'deployment', 'monitoring'],
    tools: ['docker', 'grafana'],
    icon: '\u25D5',
    orgClass: 'Specialist',
    provider: 'anthropic',
    model: 'claude-haiku-4-5-20251001',
    raisonDetre: 'Infrastructure management, deployment orchestration, and monitoring.',
  },
];

export function getAgentById(id: string): Agent | undefined {
  return agents.find((a) => a.id === id);
}

export function getChildren(parentId: string): Agent[] {
  return agents.filter((a) => a.parentId === parentId);
}
